### ISSUE TITLE
Cannot find device wg0

### ISSUE THREAD

**Issue by mueller-webservice** [perara/wg-manager#112]
Hi, I created the docker container like described. Did not change a single thing. I then configured the server and when I want to start it (press play), the following appears in the command line:

`wg-manager   | b'[#] ip link add wg0 type wireguard\nRTNETLINK answers: Operation not supported\nUnable to access interface: Protocol not supported\n[#] ip link delete dev wg0\nCannot find device "wg0"\n'`

My OS is Debian 10.
The "NET_ADMIN" cap is configured. Am I doing something wrong here? Thank you

**Comment by mueller-webservice** [comment]
Ok, solved it myself. Needed to install wireguard on the host itself from debian backports, so the hosts kernel has the wireguard module enabled. Maybe this helps someone in future.

**Comment by matzeeg3** [comment]
did not run on my side.
