### ISSUE TITLE
Allow auto-starting of wireguard server

### ISSUE THREAD

**Issue by viggy96** [perara/wg-manager#13]
It appears that upon restarting the container, the wireguard servers don't restart themselves. This is pretty much the only missing feature from this management interface.

**Comment by perara** [comment]
If i understand correctly. You would like an option that starts the WG interfaces upon start of the container/application?

**Comment by viggy96** [comment]
@perara Yup, exactly.

**Comment by simonlerpard** [comment]
I would really love this as well. If this is "the only way" to VPN into a network and you must restart the server or docker or anything dependent for any reason, it's not possible to reconnect since the Wireguard server didn't start automatically.
