### ISSUE TITLE
The page /user/edit is accessible without logging in

### ISSUE THREAD

**Issue by TR-SLimey** [perara/wg-manager#18]
While I don't think the page is functional (it's not even when logged in :laughing: ), the page should probably be made inaccessible when logged out. 

Also, as a side note, the dark theme slider is weirdly broken in that it doesn't quite know whether it's on or not when dark theme is enabled.

**Comment by perara** [comment]
This should now be fixed on the dev branch :)
 Thanks for the feedback! @TR-SLimey
