### ISSUE TITLE
Support for IPv6 please?

### ISSUE THREAD

**Issue by Haringstad** [perara/wg-manager#20]
Whow! Love the interface! The only thing that it's lacking, is IPv6 support within the docker. 

When I use 

`iptables -A FORWARD -i %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE; ip6tables -A FORWARD -i %i -j ACCEPT; ip6tables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
`

in the Post-up script, wg0 refuses to start. If I remove the ip6tables part, it works fine!
So, please advise how I can add ip6tables support to the current docker?

**Comment by perara** [comment]
Do you run the docker container in ´host´ mode?
If I understand correctly. IPV6 works fine if you remove the iptable forwards you mentioned?

**Comment by Haringstad** [comment]
I could not get it working with IPv6 at all. (Yes, connecting to the server
works) But using the private IPv6 part isn't working.
So, I guess it is missing ip6tables ??

Regards,

Jacco van Koll

**Comment by perara** [comment]
I'll take a look on this in the near future.
I have not used IPV6 myself yet, so just to confirm: The feature request here is that each client connected to the VPN should be routable via IPV6?

**Comment by Haringstad** [comment]
Per-Arne,
Yes! Exactly! And take your time on this :-)

**Comment by perara** [comment]
@Haringstad 
I've added support for IPv6. Tested OK when pinging peer-peer with ipv6 addresses.
