### ISSUE TITLE
Add new peer & edit doesn't update

### ISSUE THREAD

**Issue by iwarp** [perara/wg-manager#24]
When you add a new peer from the API or the Angular Interface, and immediately edit the name it doesn't save the changes to the name.

If you add a new peer, this returns the peer config with "id":null. 
change the name and save
The edit is looks successful by doesn't save changes with this as null.

If you reload website this peer has an ID and the edit works.

**Comment by perara** [comment]
This should now be fixed in the dev branch. Thanks for your valuable feedback! I'll close this as I'm 99% sure it is fixed, but if you still encounter the bug, please reopen :)
