### ISSUE TITLE
Method #2: Bare Metal - RuntimeError: Database does not exist and no ADMIN_USER is set

### ISSUE THREAD

**Issue by aniston** [perara/wg-manager#27]
Hi, given the screen shots this seems to be exactly what I need ;) but the Docker approach is not possible for me, so I had to go the [Method #2: Bare Metal](https://github.com/perara/wg-manager/blob/master/docs/install.md) way on a Debian 10 Server and after a clean install I followed the guidelines in Method 2#.

- on a side note in section 4. if python3-dev tools is not installed than `pip install uvicorn` will not compile so I got over that with `apt-get install python3-dev`

But the main problem comes at `uvicorn main:app --host=0.0.0.0` exits with `RuntimeError: Database does not exist and no ADMIN_USER is set`
At this point I'm not sure if the database has to be seperately created before and the admin user and password to be set by hand, if so a small how-to will help.

anyone with success on Debian bare-metal way ?

**Comment by perara** [comment]
You must set the appropriate environment variables. see https://github.com/perara/wg-manager#environment-variables

**Comment by aniston** [comment]
That worked ! straight on target and thanks for the quick reply :+1: 

I see you already clarified the error message meaning in the code output.

good work and best regards,
Ansiton.
