### ISSUE TITLE
When are you going to release the full mesh VPN Network mgmt console

### ISSUE THREAD

**Issue by taher9990** [perara/wg-manager#30]
Hi

I appreciate your done, it was great, but i have a question When are you going to release the full mesh VPN Network mgmt console

**Comment by perara** [comment]
https://www.wireguard.com/todo/
When wg-dynamic is ready, I will gladly implement it 😊

**Comment by taher9990** [comment]
Hi

But this is regarding dynamic public IPs, but what I requested was to have a full mesh of networking with auto advertising of any new changes in the topology, 
E.g. I should be able to add new peers via the GUI and these peers should be added automatically to all other existing peers in the topology.
If I delete or change the keys of one peer or I remove the the peer config from GUI, it should be reflected to the whole topology .

**Comment by perara** [comment]
If you read more closely, the wg team plan the feature to appear as part of wg-dynamic:

> It is possible to build a mesh network out of WireGuard using WireGuard as the building block. Write a tool that builds meshes and has peers discover each other, taking into account important authentication and trust properties. **Build onto of wg-dynamic.**

Therefore, to not invent the wheel twice, I will await this future until wg-dynamic is ready

**Comment by taher9990** [comment]
True, thanks a lot for your fast response
