### ISSUE TITLE
steps for bare metal install

### ISSUE THREAD

**Issue by barryboom** [perara/wg-manager#31]
forgive me if this is wrong but been trying to use the instructions for a bare metal install which i am assuming is meant for installing directly on a server and not running in docker?

However seems to fail to install and around the backend and frontend sections 

can you verify this should work and give a presistent server even if rebooted on Ubuntu 20.04.1 without havng to use docker?

**Comment by Lombra** [comment]
I made a few changes in order to get it working on Debian 10.

Install Node 12 instead of 13. (which is unsupported) 12 is long term supported. Did not try 14.
```bash
curl -sL https://deb.nodesource.com/setup_13.x | sudo bash -
```

Add `--unsafe-perm` to fix Node modules permission error.
```bash
sudo npm install --unsafe-perm > /dev/null && sudo npm install @angular/cli > /dev/null
```

Install pip modules using sudo and pip3.
```bash
sudo pip3 install -r requirements.txt
sudo pip3 install uvicorn
```

Run uvicorn using sudo. By now you need to have set the admin username and password environment variables. For my initial test I just set them when starting the server.
```bash
sudo ADMIN_USERNAME=admin ADMIN_PASSWORD=admin uvicorn main:app --host=0.0.0.0
```
```bash
sudo uvicorn main:app --host=0.0.0.0
```

**Comment by perara** [comment]
Thanks! I'll update the documentation !

**Comment by pw44** [comment]
For bare metal installation, may i ask for some help?

how to make use of a server digital certficate?
how to start by boot time?
how to change login and password, i.e, make use of linux authentication?

Thx!

**Comment by outbackdingo** [comment]
Id also like to know the answers to below 

how to make use of a server digital certficate?
how to start by boot time?
how to change login and password, i.e, make use of linux authentication?

**Comment by perara** [comment]
1. I would  think this is possible with gunicorn/uvicorn
https://docs.gunicorn.org/en/0.17.0/news.html

2. Systemd script. Can probably create something for this

3. Currently not supported, but certainly a sensible thing to add

**Comment by outbackdingo** [comment]
1. Thanks ill follow up on it
2. yeah dont quite follow the gunicorn stuff, i did mine based on bare metal without the virtual environment, so tried to fiogure out a superviser systemd file and failed miserably.
3. the only application ove ever seen with a non-changeable easy to use login, anyone who finds the site can login and create a vpn tunnel.. this is what i call a security risk. be very nice to have it resolved.

**Comment by perara** [comment]
I fully understand your concern regarding the auth system. Generally
speaking, i recommmend keeping the dashboard well hidden behind firewalls.
But ill investigate if itz feasable to extend the to support auth0 and pam
auth

**Comment by outbackdingo** [comment]
yes, this worked nicely, it should be added to the documents.
