### ISSUE TITLE
An error when starting the docker, please can you help ? I 

### ISSUE THREAD

**Issue by magefesa** [perara/wg-manager#41]
I ve installed the docker, and when starting it from portainer throws an error:

Error starting
userland proxy: listen udp
0.0.0.0:51820: bind: address
already in use

Anyone can help with these ? 51820 is the wireguard port, and yes, its in use. But how can i solve this ?

Thanks in advance

**Comment by hsosa88** [comment]
Do you have another wireguard instance running in your server??

**Comment by hsosa88** [comment]
> I ve installed the docker, and when starting it from portainer throws an error:
> 
> Error starting
> userland proxy: listen udp
> 0.0.0.0:51820: bind: address
> already in use
> 
> Anyone can help with these ? 51820 is the wireguard port, and yes, its in use. But how can i solve this ?
> 
> Thanks in advance

Do you have another wireguard instance running in your server??

**Comment by Zixim** [comment]
@magefesa I ran into the same thing.
My thinking was that I needed to run wireguard on the docker host.
But you shouldn't do that, Running (starting/stopping) is handled on the container.

**Comment by tony1661** [comment]
That port is already being used on your host. Try typing "netstat -tulpn | grep 50802” to see what is using it. Probably another instance of Wireguard as @hsosa88 said

**Comment by mewforest** [comment]
Same problem for me:

```
Creating wg-manager ...
Creating wg-manager ... error

ERROR: for wg-manager  Cannot start service wireguard: driver failed programming external connectivity on endpoint wg-manager (0e95dccebeca53721102b8117aa4ea11262984c856d4840b6822ac51ee931ee5): Error starting userland proxy: listen udp4 0.0.0.0:51820: bind: address already in use

ERROR: for wireguard  Cannot start service wireguard: driver failed programming external connectivity on endpoint wg-manager (0e95dccebeca53721102b8117aa4ea11262984c856d4840b6822ac51ee931ee5): Error starting userland proxy: listen udp4 0.0.0.0:51820: bind: address already in use
ERROR: Encountered errors while bringing up the project.
```

**Comment by tony1661** [comment]
@mewforest did you check if there is something already running on that port on the host?
