### ISSUE TITLE
Issues : RuntimeError

### ISSUE THREAD

**Issue by hayleyshim** [perara/wg-manager#48]
Hello,

I want to use wireguard configuration file manager in my local server.

So, I followed the install guide in bare metal 'ubuntu-18.04'

I have an issue 'raise RuntimeError("Database does not exist and the environment variable ADMIN_USERNAME is set")
RuntimeError: Database does not exist and the environment variable ADMIN_USERNAME is set'

Should I set the DB information? 
Please advise to me. I attached the error message below.

![image](https://user-images.githubusercontent.com/8789789/101875886-c509fd00-3bce-11eb-9531-385d7639f24c.png)

**Comment by hayleyshim** [comment]
I tried the command 'sudo ADMIN_USERNAME=admin ADMIN_PASSWORD=admin uvicorn main:app --host=0.0.0.0' 

and I can see the image

![image](https://user-images.githubusercontent.com/8789789/101876821-6776b000-3bd0-11eb-9644-37ace1846cdb.png)

but, I can't access the server on http://0.0.0.0:8000

It maybe my PC environment.
I installed this source in virtualbox VM.

So, I'll try to solve this problem ( port forwarding )

**Comment by tony1661** [comment]
Hi, were you able to fix this? Navigating to http:0.0.0.0:8000 won't work. Let me know if you still need help

**Comment by tony1661** [comment]
@hayleyshim Hi, were you able to fix this? Navigating to http:0.0.0.0:8000 won't work. Let me know if you still need help

**Comment by hayleyshim** [comment]
> @hayleyshim Hi, were you able to fix this? Navigating to http:0.0.0.0:8000 won't work. Let me know if you still need help

I fixed it, I accessed by http://localhost:8000.

After I generate wireguard conf file and put in this server, how can I manage the conf file?

I aslo have to install this source in every client PC which I want to manage configuration file?

for example, If I have to manage more tha  200 users, I need to install every client PC?

I want to figure out the process or history management about configuation files.

Please tell me it is possible or not.

**Comment by tony1661** [comment]
> After I generate wireguard conf file and put in this server, how can I manage the conf file?

What do you mean manage the file?


> I aslo have to install this source in every client PC which I want to manage configuration file?
> 
> for example, If I have to manage more tha 200 users, I need to install every client PC?

You can use the web interface to hold all your configuration files. When you are ready to install on a client PC/Mobile device you can export the file. Each client PC will need Wireguard installed.

**Comment by hayleyshim** [comment]
Okay, I got it.

In my case, I'll launch wireguard VPN service attached with router and want to monitor each client configuration file in the server.

But, we couldn't install this source in each PC/mobile so I'll find another method to manage client configuration files.

Thank you for your source and advice!
Anyway, it's a useful tool I think.

I will test another things.
If you know any other configuration file monitor source/tools, please recommend me🙂

**Comment by tony1661** [comment]
Hi. You won't need to install this app on each users PC. Once the config is generated, you can export it as a file and send it to your users.

If they are on mobile you can get them to scan the QR code.

The easiest way is to use the docker method because it has wireguard built-in and will manage the server config for you.

Client configs are all held on the server so once deployed they just stay there. No need to have wg-manager on each PC.

Hope that helps 🙂✌🏻

**Comment by hayleyshim** [comment]
So, you mean I just manage all configuration files in the server?! 
I don't need to install to the client, right?

I will test in docker environment and then import all configuration files.

After that, if I have any questions, I will tell you.

Thanks for your advice!

**Comment by tony1661** [comment]
> So, you mean I just manage all configuration files in the server?!
> I don't need to install to the client, right?

Exactly. Think of this application as a configuration manager. It should usually be installed on your Wireguard server. It will manage and apply the server configuration to your Wireguard server. It then gives you the ability to generate client configurations. It will store those configurations and apply them to the server.

In a "vanilla" wireguard install, if you wanted to setup a new client (in wireguard terms it's called a "peer") you'd need to do the following:

1. Generate private and public keys on the client
2. Type out a tunnel configuration manually for your client
3. Add a [Peer] to your server configuration
4. Add each others PublicKey to each others configs

wg-manager will do all that for you. It will do the following automatically:

1. generate your public/private keys
2. create the client tunnel config (and store it on the server)
3. Add the Peer to your server
4. exchange the PublicKeys for you

Hopefully I'm not repeating info you already know 🙂

The docker container simplifies everything. I use Ubuntu 20.04 personally but it'll work the same in 18.04 if you are set on that release. Docker will make your life easier. If you need a hand let me know ✌🏻
