### ISSUE TITLE
unable to change admin password

### ISSUE THREAD

**Issue by magik20** [perara/wg-manager#68]
Using Centos 7 and Docker

In the compose file, I tried changing the 

      ADMIN_PASSWORD: admin
      ADMIN_USERNAME: admin

variables and re-running compose, but the password seemingly never changed.  I was unable to login using the new password and was forced to use admin/admin.

I tried a few times.

**Comment by perara** [comment]
The password will not change when running these again. Those env variables only work on first setup. You will have to navigate to edit user page to change password: https://github.com/perara/wg-manager/blob/main/wg-manager-backend/routers/v1/user.py#L24
