### ISSUE TITLE
wg0 not going to start

### ISSUE THREAD

**Issue by reentier** [perara/wg-manager#74]
wg0 will not go up after a fresh installation:

<img width="806" alt="image" src="https://user-images.githubusercontent.com/77726631/105519331-9311ad80-5cd9-11eb-9178-232c9132fa76.png">

I'm getting the following error:

<img width="978" alt="image" src="https://user-images.githubusercontent.com/77726631/105519460-b9cfe400-5cd9-11eb-9ad9-78a872f17cf7.png">

Can anybody give advise how to fix this problem?

regards

**Comment by kdkavanagh** [comment]
Same error here using docker-compose install.  Have you been able to get past this?

**Comment by kdkavanagh** [comment]
Looks like I needed to open a shell into the container and manually `apt-get update && apt-get install iproute2`.

Does `iproute2` need to be explicitly added to the dockerfile @perara?

**Comment by reentier** [comment]
> Looks like I needed to open a shell into the container and manually `apt-get update && apt-get install iproute2`.
> 
> Does `iproute2` need to be explicitly added to the dockerfile @perara?

This worked for me too. What will happen in case of updating the container? Do i have to reinstall this package?

**Comment by kdkavanagh** [comment]
Any updates to the container will wipe this install, requiring you to repeat the manual installation.  Easy fix is to add the package to the dockerfile, however I dont entirely understand why it was necessary to install this in the first place, assuming others have gotten the docker-based install to work as-is.

**Comment by tromlet** [comment]
Yeah, I got these exact same errors (on CentOS 7). :/
