### ISSUE TITLE
AUTOSTART_INTERFACES doesn't work when restarting docker host

### ISSUE THREAD

**Issue by Zixim** [perara/wg-manager#77]
I have 
AUTOSTART_INTERFACES = wg0

When I restart the container, wg0 comes up as expected.
When I restart the docker host, the container comes up but wg0 doesn't come up.

I don't even know how to start troubleshooting this ...
halp plz ?

**Comment by Zixim** [comment]
closing, I can no longer reproduce...

**Comment by perara** [comment]
@Zixim So this is now working as expected?

**Comment by Zixim** [comment]
I guess so? It was 100% reproducible...it isn't anymore.
