### ISSUE TITLE
cant login with user: admin, password: admin.

### ISSUE THREAD

**Issue by 2L3R4** [perara/wg-manager#9]
expected behavior:
show the dashboard, or watever is shown after login
actual bahavior:
"nothing" (it stays on the login page, no errors shown) on client side;
error in server console [serverlog.txt](https://github.com/perara/wg-manager/files/4521213/serverlog.txt)
[new-serverlog.txt](https://github.com/perara/wg-manager/files/4521591/serverlog.txt)

**Comment by perara** [comment]
I'm not able to reproduce.
My steps:

1. ng build
2. Copy dist to build directory in backend.
3. Delete database.db
4. Start backend
5. Start frontend and login (Works OK)
Are these similar to your approach?

* Did you try to recreate the database after the latest commit? 
* Could you perhaps see if there is a user in the database?

The process of creating a user **should** be straight forward, defined in main.py#L41

**Comment by 2L3R4** [comment]
I edited main.py L43 +L.44 (replace os.getenv(...) with just "admin"); it looks like the code cant get enviroment variables. (only me?), It now works

**Comment by perara** [comment]
Perhaps I should make it a requirement to include env variables so that it is more obvious something is wrong. Thanks for the discovery :)
